version: '3'

services:
  publisher-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: publisher_local

  filestore-app:
    build:
      context: .filestore
      dockerfile: ./Dockerfile
    ports:
      - '3006:3000'
    environment:
      SECRET_KEY_BASE: 'super_secret'

  datastore-app:
    build:
      context: .datastore
      dockerfile: ./Dockerfile
    links:
      - datastore-db
    environment:
      DATABASE_URL: "postgres://postgres:password@datastore-db/datastore_local"
      RAILS_ENV: development
      SERVICE_TOKEN: 21f0a1b35c51cf3fdbcd54bcc34e0cb3
      SECRET_KEY_BASE: "xxxyyy"
      MAX_IAT_SKEW_SECONDS: "60"
      SERVICE_TOKEN_CACHE_ROOT_URL: "http://token-cache-app:3000"
    ports:
      - 3006:3000

  datastore-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: datastore_local

  publisher-app:
    build:
      context: .publisher
      dockerfile: ./docker/web/Dockerfile
    links:
      - publisher-db
    environment:
      DATABASE_URL: "postgres://postgres:password@publisher-db/publisher_local"
      SECRET_KEY_BASE: "xxxyyy"
    ports:
      - 3005:3000

  publisher-worker:
    build:
      context: .publisher
      dockerfile: docker/worker/Dockerfile
    environment:
      REDISCLOUD_URL: "publisher-redis"
      QUEUE: "*"
    links:
      - publisher-redis
    depends_on:
      - publisher-app
    ports:
      - 8000:80

  runner-app:
    build:
      context: .runner
      dockerfile: Dockerfile
    ports:
      - 3003:3000
    environment:
      SERVICE_PATH: /home/deploy/.test-form
      SUBMITTER_URL: http://submitter-app:3000
      USER_DATASTORE_URL: http://datastore-app:3000
      USER_FILESTORE_URL: http://filestore:3000
      SERVICE_SECRET: cd460e88c498b133ad11527e79a3d4ac
      SERVICE_TOKEN: 8a7dc8f85a0b8245598eb07098304347
      SERVICE_SLUG: slug
    volumes:
      - ".test-form:/home/deploy/.test-form"

  submitter-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: submitter_local

  submitter-app:
    build:
      context: .submitter
      dockerfile: ./docker/api/Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@submitter-db/submitter_local"
      NOTIFY_EMAIL_GENERIC: '46a72b64-9541-4000-91a7-fa8a3fa10bf9'
      NOTIFY_EMAIL_RETURN_SETUP_EMAIL_TOKEN: '38f6a1cd-a810-4f59-8899-2c300236c5b4'
      NOTIFY_EMAIL_RETURN_SETUP_EMAIL_VERIFIED: ''
      NOTIFY_EMAIL_RETURN_SETUP_MOBILE_VERIFIED: '54dcaad7-4967-431d-8606-72b0b80b5c6a'
      NOTIFY_EMAIL_RETURN_SIGNIN_EMAIL: ''
      NOTIFY_EMAIL_RETURN_SIGNIN_SUCCESS: ''
      NOTIFY_SMS_GENERIC: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'
      NOTIFY_SMS_RETURN_SETUP_MOBILE: '54dcaad7-4967-431d-8606-72b0b80b5c6a'
      NOTIFY_SMS_RETURN_SIGNIN_MOBILE: 'something'
      NOTIFY_SMS_RETURN_SETUP_MOBILE: '54dcaad7-4967-431d-8606-72b0b80b5c6a'
      FB_ENVIRONMENT_SLUG: 'test'
      SECRET_KEY_BASE: 'xxxyyy'
      PDF_GENERATOR_ROOT_URL: 'pdf-generator:3000'
    links:
      - submitter-db

  submitter-worker:
    build:
      context: .submitter
      dockerfile: ./docker/worker/Dockerfile
    environment:
      DATABASE_URL: "postgres://postgres:password@submitter-db/submitter_local"
      NOTIFY_EMAIL_GENERIC: '46a72b64-9541-4000-91a7-fa8a3fa10bf9'
      NOTIFY_EMAIL_RETURN_SETUP_EMAIL_TOKEN: '38f6a1cd-a810-4f59-8899-2c300236c5b4'
      NOTIFY_EMAIL_RETURN_SETUP_EMAIL_VERIFIED: ''
      NOTIFY_EMAIL_RETURN_SETUP_MOBILE_VERIFIED: '54dcaad7-4967-431d-8606-72b0b80b5c6a'
      NOTIFY_EMAIL_RETURN_SIGNIN_EMAIL: ''
      NOTIFY_EMAIL_RETURN_SIGNIN_SUCCESS: ''
      NOTIFY_SMS_GENERIC: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'
      NOTIFY_SMS_RETURN_SETUP_MOBILE: '54dcaad7-4967-431d-8606-72b0b80b5c6a'
      NOTIFY_SMS_RETURN_SIGNIN_MOBILE: 'something'
      NOTIFY_SMS_RETURN_SETUP_MOBILE: '54dcaad7-4967-431d-8606-72b0b80b5c6a'
      FB_ENVIRONMENT_SLUG: 'test'
      SECRET_KEY_BASE: 'xxxyyy'
      PDF_GENERATOR_ROOT_URL: 'pdf-generator:3000'
    links:
      - submitter-db
    command: bundle exec rake jobs:work

  token-cache-app:
    build:
      context: .token-cache
      dockerfile: ./Dockerfile
    ports:
      - 3004:3000
    environment:
      SECRET_KEY_BASE: 'super_secret'

  av-app:
    build:
      context: .av
      dockerfile: ./Dockerfile

  pdf-generator:
    build:
      context: .pdf-generator
      dockerfile: ./Dockerfile
    environment:
      SERVICE_TOKEN_CACHE_ROOT_URL: "token-cache-app:3000"
      SENTRY_DSN: 'whatever'

  publisher-redis:
    image: 'bitnami/redis:5.0'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
